# =============================================================================
# E.O.P IDENTITY SERVICE — application.properties
# Port 8081 | PostgreSQL (eop_identity_db)
# =============================================================================

server.port=8081
spring.application.name=eop-identity

# =============================================================================
# POSTGRESQL — eop_identity_db
# =============================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/eop_identity_db
spring.datasource.username = postgres
spring.datasource.password = rechyone
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =============================================================================
# JWT — Secret key WAJIB identik dengan Gateway
# =============================================================================
jwt.secret=Priestess_EOP_UAS_Secret_Key_2025_Secure!

# =============================================================================
# LOGGING
# =============================================================================
logging.level.com.priestess.identity=DEBUG
