# =============================================================================
# E.O.P CORE FINANCE SERVICE — application.properties
# Port 8082 | PostgreSQL (wallets, vouchers) + MongoDB (transactions)
# =============================================================================

server.port=8082
spring.application.name=eop-core-finance

# =============================================================================
# POSTGRESQL — eop_finance_db
# =============================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/eop_finance_db
spring.datasource.username = postgres
spring.datasource.password = rechyone
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =============================================================================
# MONGODB — eop_transaction_log
# =============================================================================
spring.data.mongodb.uri=mongodb://localhost:27017/eop_transaction_log

# =============================================================================
# LOGGING
# =============================================================================
logging.level.com.priestess.core=DEBUG
